### ISSUE TITLE
Reader Object Error

### ISSUE THREAD

**Issue by nickeener** [blankenberg/nvc#3]
Hey not sure if this is still being maintained but it's worth a shot. I'm comparing a number of variant callers, one of which is nvc, but I'm having problems getting it to run. I installed it using conda in an environment with python 2 but the error looks like a problem with the code itself. Any help would be greatly appreciated. I'll copy the error message below:

> Traceback (most recent call last):
  File "/home/nickeener/anaconda3/envs/py2/bin/naive_variant_caller.py", line 94, in <module>
    if __name__ == "__main__": main()
  File "/home/nickeener/anaconda3/envs/py2/bin/naive_variant_caller.py", line 89, in main
    allow_out_of_bounds_positions=options.allow_out_of_bounds_positions, safe=options.safe )
  File "/home/nickeener/anaconda3/envs/py2/lib/python2.7/site-packages/pyBamTools/genotyping/naive.py", line 93, in __init__
    self._dtypes = guess_numpy_dtypes_from_idxstats( bam_readers, dtype, force_dtype=force_dtype )
  File "/home/nickeener/anaconda3/envs/py2/lib/python2.7/site-packages/pyBamTools/util/__init__.py", line 41, in guess_numpy_dtypes_from_idxstats
    refs = bam_index._references
AttributeError: 'Reader' object has no attribute '_references'

**Comment by nekrut** [comment]
@blankenberg can you take a look at this? We unfortunately cannot use `nvc` for anything meaningful for that reason.

**Comment by blankenberg** [comment]
Sorry for the delay (I missed this issue being opened) and more sorry to hear that you are experiencing issues.

First guess is that your BAM file is not index, with e.g. samtools:
samtools index my_alignment.bam

I should definitely make this issue clearer though.

If you have a xyz.bam.bai next to your xyz.bam input and it is not working, let me know and I will dig deeper.

Please let me know how it goes. Of course, this error message is not super helpful and should be enhanced, regardless.


Thanks,

Dan

**Comment by nickeener** [comment]
@blankenberg 
You were right, I forgot to create the bam index file. However, I did so (using bamtools index) but now I'm getting a different error:

> BAM Index appears to be malformed: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'.

I've run this dataset on other variant callers (freebayes, gatk Mutect2, and snippy) and haven't gotten any error messages regarding the bam index.

Here's the command I'm running:
`naive_variant_caller.py -b FVM.bam -o nvc/FVM.vcf -r FVM.fasta -p 1`

**Comment by blankenberg** [comment]
@nickeener would you be able to share a link to the input bam and bai files? Feel free to email me directly with them if you like.

**Comment by nickeener** [comment]
@blankenberg See: https://github.com/nickeener/HIV
The FVM.bam and FVM.bam.bai are the relevant files.
Thanks!

**Comment by blankenberg** [comment]
The input BAM file (https://github.com/nickeener/HIV/blob/master/FVM.bam) is unsorted, and the index created by bamtools is more-or-less empty. 

I would have thought that BAMtools would raise an error on indexing here, but I checked and it doesn't; samtools does raise an error, however.
```
$ bamtools index -in FVM.bam
```

```
$ samtools index FVM.bam
[E::hts_idx_push] Unsorted positions on sequence #5: 2257 followed by 1802
samtools index: failed to create index for "FVM.bam"
```

Can you sort your BAM file first, then index, then try NVC again?

**Comment by nickeener** [comment]
@blankenberg That did it. Thanks for the help.
